image: Visual Studio 2019

environment:
  matrix:
    - MSYSTEM: MINGW32
    - MSYSTEM: MINGW64

install:
  - git submodule update --init --recursive
  - set PATH=C:/msys64/usr/bin;%PATH%
  - sh -l -c "pacman --noconfirm -S --needed base-devel ${MINGW_PACKAGE_PREFIX}-toolchain ${MINGW_PACKAGE_PREFIX}-libevent ${MINGW_PACKAGE_PREFIX}-openssl ${MINGW_PACKAGE_PREFIX}-postgresql autoconf automake libtool python zip"
  - choco install pandoc

build_script:
  - set HOME=.
  - set PATH=C:/msys64/usr/bin;%PATH%
  - sh -l -c "./autogen.sh"
  - sh -l -c "./configure --enable-werror"
  - sh -l -c "make"
  - sh -l -c "make install"
  - sh -l -c "make zip"

artifacts:
  - path: '*.zip'

test_script:
  - set HOME=.
  - set PATH=C:/msys64/usr/bin;%PATH%
  - sh -l -c "cd test/ && ./test.sh"

on_failure:
  - set HOME=.
  - sh -l -c "test -f config.status || cat config.log"
  - sh -l -c "find test/ -name '*.log' | xargs tail -n40 -v"
