image: Visual Studio 2019

environment:
  matrix:
    - MSYSTEM: MINGW32
    - MSYSTEM: MINGW64

install:
  - git submodule update --init --recursive
  - set PATH=C:/msys64/usr/bin;%PATH%
  - choco install -y --no-progress msys2
  - sh -l -c "pacman --noconfirm -S --needed base-devel ${MINGW_PACKAGE_PREFIX}-gcc ${MINGW_PACKAGE_PREFIX}-libevent ${MINGW_PACKAGE_PREFIX}-openssl ${MINGW_PACKAGE_PREFIX}-postgresql autoconf automake libtool ${MINGW_PACKAGE_PREFIX}-python ${MINGW_PACKAGE_PREFIX}-python-pip zip"
  - sh -l -c 'pip install -r /c/projects/pgbouncer-pgbouncer/requirements.txt'
  - choco install -y --no-progress pandoc

build_script:
  - set HOME=.
  - set PATH=C:/msys64/usr/bin;%PATH%
  - sh -l -c "./autogen.sh"
  - sh -l -c "./configure --enable-werror LDFLAGS=-static LIBS=-liphlpapi PKG_CONFIG='pkg-config --static'"
  - sh -l -c "make"
  - sh -l -c "make install"
  - sh -l -c "make zip"

artifacts:
  - path: '*.zip'

test_script:
  - set HOME=.
  - set PATH=C:/msys64/usr/bin;%PATH%
  - sh -l -c "make check tls_support=no"
  - sh -l -c "windres pgbouncer.exe"

on_failure:
  - set HOME=.
  - sh -l -c "test -f config.status || cat config.log"
  - sh -l -c "find test/ -name '*.log' | xargs tail -n40 -v"
